version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-container
    ports:
      - "1433:1433"  
    environment:
      - SA_PASSWORD=MyStrong@Password2024
      - ACCEPT_EULA=Y  
    volumes:
      - sqlserver-data:/var/opt/mssql 

volumes:
  sqlserver-data:
